version: "3.3"
services:
  helloapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - "default"
  prometheus:
    image: bitnami/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - "default"
    links:
      - helloapp
    depends_on:
      - helloapp

networks:
  default: