global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'helloapp-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:9090']
  
  - job_name: 'helloapp'
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:8080']